import { GoogleOAuthProvider } from '@react-oauth/google'; // Import the provider
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID; // Replace with your actual Google Client ID

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the app with GoogleOAuthProvider */}
        <GoogleOAuthProvider clientId={`${googleClientId}`}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
